title: Junya Tanaka
baseurl: ""
url: "https://tanajun99.github.io"
google_analytics: "UA-60340700-2" # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Junya Tanaka | 田中潤也
  desc: Master Student/Research Engineer
  email: tanajun.99@gmail.com
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: junya.tanaka.942
  flickr:
  github: tanajun99
  google_plus:
  instagram: junyadidntwakeup
  keybase:
  linkedin: https://www.linkedin.com/in/tanajun99/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: tanajun99
  vimeo:
  wordpress: https://tanajun99.hatenablog.com/
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"